config/routes.rb
Rails.application.routes.draw do

  root :to => 'articles#index'

  resources :articles do
    resources :comments
  end
  resources :users
  
  post 'users/new' => 'sessions#create'

  delete 'logout' => 'sessions#destroy', :as => :logout

end

app/models/article.rb
class Article < ActiveRecord::Base
	has_many :comments
	belongs_to :user
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :article
end

app/models/user.rb
class User < ActiveRecord::Base
	validates_confirmation_of :password
	validates :username, uniqueness: true
	has_secure_password
	
	has_many :articles
	has_many :comments

	before_save { self.username = username.downcase }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
		return unless session[:user_id]
    	@current_user ||= User.find(session[:user_id])
  end

  def require_ownership
		if !current_user || current_user.id != Article.find(params[:id]).user_id
			flash[:alert] = "Permission Required To Edit"
			redirect_to root_path
		end
  end 

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

	before_action :require_ownership, only: :edit

	def index
		@articles = Article.order("created_at DESC")
	end

	def new
		unless current_user
			flash[:alert] = "Please Login or Signup first"
			redirect_to '/'
		else
			@article = current_user.articles.build
		end
	end

	def create
		return redirect_to '/', flash[:alert] = "Please Login or Signup first" unless current_user

		@article = current_user.articles.build(article_params)
		if @article.save
			redirect_to article_path(@article)
		else
			flash[:alert] = "Article Creation Failed, Please Try Again"
			redirect_to new_article_path
		end
	end

	def show
		@article = Article.find(params[:id])
	end

	def edit
		@article = Article.find(params[:id])
	end

	def update
		@article = Article.find(params[:id])
		if @article.update_attributes(article_params)
			redirect_to article_path(@article)
		else
			flash[:alert] = "Editing Unsuccessful, Please Try Again"
		end
	end

	private
	def article_params
		params.require(:article).permit(:title, :body)
	end

	
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		@user = User.find_by_username(params[:username])

		if @user && @user.authenticate(params[:password])
			session[:user_id] = @user.id
			redirect_to '/'
		else
			redirect_to '/'
			flash[:alert] = "Invalid Login Attempt"
		end
	end

	def destroy
		session.clear
		redirect_to root_path
	end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
	def create
		@user = User.new(user_params)
		@problems = Problem.all
		if @user.save
			sign_in(@user)
			redirect_to root_path
		else
			alert("Email has already been taken")
		end
	end

	def new
		@user = User.new
	end

	def user_params
		params.require(:user).permit(:username, :password, :password_confirmation)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			flash[:alert] = "Success"
			redirect_to '/users'
		else
			flash[:alert] = "Unsuccessful Account Creation"
			redirect_to '/'
		end
	end

	def user_params
		params.require(:user).permit(:username, :password, :password_confirmation)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def current_user
		return unless session[:user_id]
    	@current_user ||= User.find(session[:user_id])
	end
end

app/helpers/articles_helper.rb
module ArticlesHelper
	def current_user
		return unless session[:user_id]
    	@current_user ||= User.find(session[:user_id])
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/session_helper.rb
module SessionHelper
	def current_user
		return unless session[:user_id]
    @current_user ||= User.find(session[:user_id])
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def current_user
		return unless session[:user_id]
    	@current_user ||= User.find(session[:user_id])
	end

	def display_session_partials
		if session[:user_id]
			render 'sessions/logout'
		else
			render 'sessions/new'
			render 'users/new'
		end
	end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/articles/edit.html.erb
<h2>Edit Article</h2>
<%= form_for @article do |f| %>
	<p>
		<%= f.label :title %><br>
		<%= f.text_field :title %>
	</p>

	<p>
		<%= f.label :body %><br>
		<%= f.text_area :body %>
	</p>

	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/articles/index.html.erb
  <div>
	<% @articles.each do |article| %>
		<h2><%= link_to article.title, article  %></h2>
		<br>
		<h3><%= article.user.username %> - <%= time_ago_in_words(article.created_at) %></h3>
		<br>
		<br>
	<% end %>
  </div>

app/views/articles/new.html.erb
<h2>New Article</h2>
<%= form_for @article do |f| %>
	<p>
		<%= f.label :title %><br>
		<%= f.text_field :title %>
	</p>

	<p>
		<%= f.label :body %><br>
		<%= f.text_area :body %>
	</p>

	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/articles/show.html.erb
<div>
	<h2><%= @article.title %></h2>
	<br>
	<h3><%= @article.user.username %> - <%= time_ago_in_words(@article.created_at) %></h3>
	<br>
	<%=  @article.body %>
	<br>
		<% if current_user && current_user.id == @article.user_id %>
		  <%= link_to "edit", edit_article_path %>
		<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Getintoit</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'shared/navbar' %>

<% if session[:user_id] %>
	<%=	render 'sessions/logout' %>
<% else %>
	<%= render 'sessions/new' %>
	<%= render 'users/new' %>
<% end %>

<% if flash[:alert] %>
	<div class="alert"><%= flash[:alert] %></div>
<% end %>

<%= yield %>

</body>
</html>

app/views/shared/_navbar.html.erb
<header>
<h1> <%= link_to "Get Into It", root_path %> </h1> <h2> <%= link_to "New Article", new_article_path if current_user %> </h2>
</header>

app/views/users/_new.html.erb
<%= form_for :user, url: users_path do |f| %>
	<%= f.text_field :username, :placeholder => "Username" %>
	<%= f.password_field :password, :placeholder => "Password" %>
	<%= f.password_field :password_confirmation, :placeholder => "Password Confirmation" %>
	<%= f.submit "Create Account", :disable_with => "Creating..." %>
<% end %>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
	<%= f.text_field :username, :placeholder => "Username" %>
	<%= f.password_field :password, :placeholder => "Password" %>
	<%= f.password_field :password_confirmation, :placeholder => "Password Confirmation" %>
	<%= f.submit "Create Account", :disable_with => "Creating..." %>
<% end %>

app/views/users/show.html.erb
HELLO